/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/ny/ny.glb');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane085.geometry}
        material={nodes.Plane085.material}
        position={[8.4, 1, -4.85]}
        scale={[1, 1.86, 1]}
      />
    </group>
  )
}

useGLTF.preload('/models/ny/ny.glb')
