/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/states/usa.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane007.geometry}
        material={nodes.Plane007.material}
        position={[6.26, 0, 4.52]}
        scale={[1, 1.41, 1]}
      />
      <mesh
        geometry={nodes.Plane006.geometry}
        material={nodes.Plane006.material}
        position={[6.01, 0, 2.04]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane004.geometry}
        material={nodes.Plane004.material}
        position={[6.96, 0, 1.15]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={nodes.Plane003.material}
        position={[10.2, 0, -4.58]}
        scale={[1, 1.4, 1]}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={nodes.Plane002.material}
        position={[10.24, 0, -4.88]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={nodes.Plane001.material}
        position={[9.36, 0, -5.92]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane000.geometry}
        material={nodes.Plane000.material}
        position={[9.94, 0, -5.84]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane087.geometry}
        material={nodes.Plane087.material}
        position={[9.74, 0, -4.41]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane085.geometry}
        material={nodes.Plane085.material}
        position={[8.4, 0, -4.85]}
        scale={[1, 1.54, 1]}
      />
      <mesh
        geometry={nodes.Plane084.geometry}
        material={nodes.Plane084.material}
        position={[9.04, 0, -3.26]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane083.geometry}
        material={nodes.Plane083.material}
        position={[7.96, 0, -3.69]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane082.geometry}
        material={nodes.Plane082.material}
        position={[8.87, 0, -2.58]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane081.geometry}
        material={nodes.Plane081.material}
        position={[8.13, 0, -2.37]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane080.geometry}
        material={nodes.Plane080.material}
        position={[7.6, 0, -1.51]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane078.geometry}
        material={nodes.Plane078.material}
        position={[6.63, 0, -1.95]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane077.geometry}
        material={nodes.Plane077.material}
        position={[5.36, 0, -2.63]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane076.geometry}
        material={nodes.Plane076.material}
        position={[3.64, 0, -1.67]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane075.geometry}
        material={nodes.Plane075.material}
        position={[3.69, 0, -5.33]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane073.geometry}
        material={nodes.Plane073.material}
        position={[4.18, 0, -1.07]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane072.geometry}
        material={nodes.Plane072.material}
        position={[7.83, 0, 0]}
        scale={[1, 1.48, 1]}
      />
      <mesh
        geometry={nodes.Plane071.geometry}
        material={nodes.Plane071.material}
        position={[4.49, 0, 0.16]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane068.geometry}
        material={nodes.Plane068.material}
        position={[10.67, 0, -7.25]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane067.geometry}
        material={nodes.Plane067.material}
        position={[3.62, 0, 3.05]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane066.geometry}
        material={nodes.Plane066.material}
        position={[2.28, 0, 2.83]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane065.geometry}
        material={nodes.Plane065.material}
        position={[1.65, 0, 3.89]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane064.geometry}
        material={nodes.Plane064.material}
        position={[1.23, 0, 1.13]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane063.geometry}
        material={nodes.Plane063.material}
        position={[1.35, 0, -0.98]}
        scale={[1, 1.37, 1]}
      />
      <mesh
        geometry={nodes.Plane062.geometry}
        material={nodes.Plane062.material}
        position={[2.07, 0, -1.96]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane061.geometry}
        material={nodes.Plane061.material}
        position={[1.56, 0, -5.33]}
        scale={[1, 1.41, 1]}
      />
      <mesh
        geometry={nodes.Plane060.geometry}
        material={nodes.Plane060.material}
        position={[0.1, 0, -6.33]}
        scale={[1, 1.51, 1]}
      />
      <mesh
        geometry={nodes.Plane059.geometry}
        material={nodes.Plane059.material}
        position={[0.76, 0, -3.35]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane058.geometry}
        material={nodes.Plane058.material}
        position={[-2.23, 0, 3.73]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane057.geometry}
        material={nodes.Plane057.material}
        position={[-1.95, 0, 1.19]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane056.geometry}
        material={nodes.Plane056.material}
        position={[-1.4, 0, -1.4]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane055.geometry}
        material={nodes.Plane055.material}
        position={[-2.2, 0, -3.1]}
        scale={[1, 1.52, 1]}
      />
      <mesh
        geometry={nodes.Plane054.geometry}
        material={nodes.Plane054.material}
        position={[-2.13, 0, -4.71]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane053.geometry}
        material={nodes.Plane053.material}
        position={[-1.91, 0, -6.44]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane052.geometry}
        material={nodes.Plane052.material}
        position={[-5.48, 0, -1.66]}
        scale={[1, 1.67, 1]}
      />
      <mesh
        geometry={nodes.Plane051.geometry}
        material={nodes.Plane051.material}
        position={[-6.56, 0, 2.09]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane050.geometry}
        material={nodes.Plane050.material}
        position={[-6.13, 0, -4.25]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane031.geometry}
        material={nodes.Plane031.material}
        position={[-8.15, 0, -2.59]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane030.geometry}
        material={nodes.Plane030.material}
        position={[-9.84, 0, 0.66]}
        scale={[1, 1.44, 1]}
      />
      <mesh
        geometry={nodes.Plane029.geometry}
        material={nodes.Plane029.material}
        position={[-7.87, 0, -6.75]}
        scale={[1, 1.44, 1]}
      />
      <mesh
        geometry={nodes.Plane028.geometry}
        material={nodes.Plane028.material}
        position={[-9.33, 0, -6.29]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane027.geometry}
        material={nodes.Plane027.material}
        position={[-10.32, 0, -1.51]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane026.geometry}
        material={nodes.Plane026.material}
        position={[-12.84, 0, -1.7]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane025.geometry}
        material={nodes.Plane025.material}
        position={[-11.41, 0, -6.17]}
        scale={[1, 1.94, 1]}
      />
      <mesh
        geometry={nodes.Plane024.geometry}
        material={nodes.Plane024.material}
        position={[-11.89, 0, -7.98]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane023.geometry}
        material={nodes.Plane023.material}
        position={[-9.38, 0, 6.93]}
        scale={[1, 1.29, 1]}
      />
      <mesh
        geometry={nodes.Plane005.geometry}
        material={nodes.Plane005.material}
        position={[-12.91, 0, 4.66]}
        scale={[1, 1.29, 1]}
      />
    </group>
  )
}

useGLTF.preload('/models/states/usa.glb')
