/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useCallback, useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef();
  const mesh = useRef();
  const [positionY, setPositionY] = useState(0);
  const [active, setActive] = useState(false);
  const [isHovered, setIsHovered] = useState(false);

  const { nodes, materials } = useGLTF('/models/states/usa.glb')

  const onHover = useCallback((e, v) => {
    e.stopPropagation(); //stop ref at first intersection
    e.target;
    setIsHovered(v);
    // isHovered = true
  }, [setIsHovered]);

  function handleClick() {
    setActive(v => !v);
    active ? setPositionY(0) :
    setPositionY(0.35);
  }

  return (
    <group ref={group} {...props} dispose={null}>
      {/* //--------------Florida--------------//
      <mesh
        ref={mesh}
        name='FL'
        geometry={nodes.Plane007.geometry}
        material={nodes.Plane007.material}
        position={[6.26, 0, 4.52]}
        scale={[1, 1.41, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
          color = {isHovered ? '#fff' : '#399E5A'}
        />
      </mesh> */}
      {/* //----------Georgia---------//
      <mesh
        ref={mesh}
        name='GA'
        geometry={nodes.Plane006.geometry}
        material={nodes.Plane006.material}
        position={[6.01, 0, 2.04]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
            color = {isHovered? '#fff' : '#399E5A'}
        />
      </mesh> */}
      {/* //----------South Carolina----------//
      <mesh
        ref={mesh}
        name='SC'
        geometry={nodes.Plane004.geometry}
        material={nodes.Plane004.material}
        position={[6.96, 0, 1.15]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
            color = {isHovered? '#fff' : '#399E5A'}
            />
      </mesh> */}
      {/* //----------Rhode Island---------//
      <mesh
        ref={mesh}
        name='RI'
        geometry={nodes.Plane003.geometry}
        material={nodes.Plane003.material}
        position={[10.2, 0, -4.58]}
        scale={[1, 1.4, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
          <meshStandardMaterial
            color = {isHovered? '#fff' : '#399E5A'}
          />
      </mesh> */}
      {/* //---------Massachussettes--------//
      <mesh
        ref={mesh}
        name='MA'
        geometry={nodes.Plane002.geometry}
        material={nodes.Plane002.material}
        position={[10.24, 0, -4.88]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
          color = {isHovered? '#fff' : '#399E5A'}
        />
      </mesh> */}
      {/* //---------VT---------//
      <mesh
        ref={mesh}
        name = 'VT'
        geometry={nodes.Plane001.geometry}
        material={nodes.Plane001.material}
        position={[9.36, 0, -5.92]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
          color = {isHovered? '#fff' : '#399E5A'}
        />
      </mesh> */}
      {/* //---------New Hampshire----------//
      <mesh
        ref={mesh}
        name='NH'
        geometry={nodes.Plane000.geometry}
        material={nodes.Plane000.material}
        position={[9.94, 0, -5.84]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
          color = {isHovered? '#fff' : '#399E5A'}
        />
      </mesh> */}
      {/* //---------Connecticut---------//
      <mesh
        ref={mesh}
        name= 'CT'
        geometry={nodes.Plane087.geometry}
        material={nodes.Plane087.material}
        position={[9.74, 0, -4.41]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
          color = {isHovered? '#fff' : '#399E5A'}
        />
      </mesh> */}
      {/* //--------- NY ----------//
      <mesh
        geometry={nodes.Plane085.geometry}
        material={nodes.Plane085.material}
        position={[8.4, 0, -4.85]}
        scale={[1, 1.54, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
          // color = {isHovered? '#fff' : '#399E5A'}
        />
      </mesh> */}
      {/* //----------NJ----------//
      <mesh
        ref={mesh}
        name='NJ'
        geometry={nodes.Plane084.geometry}
        material={nodes.Plane084.material}
        position={[9.04, 0, -3.26]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
          color = {isHovered? '#fff' : '#399E5A'}
        />
      </mesh> */}
      {/* //----------PA----------//
      <mesh
        ref={mesh}
        name='PA'
        geometry={nodes.Plane083.geometry}
        material={nodes.Plane083.material}
        position={[7.96, 0, -3.69]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
          color = {isHovered? '#fff' : '#399E5A'}
        />
      </mesh> */}
        {/* //----------DE----------//
      <mesh
        ref={mesh}
        name='DE'
        geometry={nodes.Plane082.geometry}
        material={nodes.Plane082.material}
        position={[8.87, 0, -2.58]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
        >
        <meshStandardMaterial
          color = {isHovered? '#fff' : '#399E5A'}
          />
      </mesh> */}
        {/* //----------MD----------//
      <mesh
        ref={mesh}
        name='MD'
        geometry={nodes.Plane081.geometry}
        material={nodes.Plane081.material}
        position={[8.13, 0, -2.37]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
        >
        <meshStandardMaterial
          color = {isHovered? '#fff' : '#399E5A'}
        />
      </mesh> */}
      {/* //----------VA----------//
      <mesh
        ref={mesh}
        name='VA'
        geometry={nodes.Plane080.geometry}
        material={nodes.Plane080.material}
        position={[7.6, 0, -1.51]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
          color = {isHovered? '#fff' : '#399E5A'}
        />
      </mesh> */}
      {/* //---------WV---------//
      <mesh
        ref={mesh}
        name='WV'
        geometry={nodes.Plane078.geometry}
        material={nodes.Plane078.material}
        position={[6.63, 0, -1.95]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
          color = {isHovered? '#fff' : '#399E5A'}
        />
      </mesh> */}
      {/* //---------OH---------//
      <mesh
        ref={mesh}
        geometry={nodes.Plane077.geometry}
        material={nodes.Plane077.material}
        position={[5.36, 0, -2.63]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
          color = {isHovered? '#fff' : '#399E5A'}
        />
      </mesh> */}
      {/* //---------IN---------//
      <mesh
        ref={mesh}
        name='IN'
        geometry={nodes.Plane076.geometry}
        material={nodes.Plane076.material}
        position={[3.64, 0, -1.67]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
          color = {isHovered? '#fff' : '#399E5A'}
        />
      </mesh> */}
      {/* //---------MI---------//
      <mesh
        ref={mesh}
        name='MI'
        geometry={nodes.Plane075.geometry}
        material={nodes.Plane075.material}
        position={[3.69, 0, -5.33]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
        >
        <meshStandardMaterial
          color = {isHovered? '#fff' : '#399E5A'}
          />
      </mesh> */}
      {/* //---------KY---------//
      <mesh
      ref={mesh}
      name='KY'
      geometry={nodes.Plane073.geometry}
      material={nodes.Plane073.material}
      position={[4.18, 0, -1.07]}
      scale={[1, 1.29, 1]}
      onPointerOver={e => onHover(e, true)}
      onPointerOut={e => onHover(e, false)}
      onClick={() => handleClick()}
      >
      <meshStandardMaterial
        color = {isHovered? '#fff' : '#399E5A'}
        />
    </mesh> */}
    {/* //---------NC---------//
      <mesh
        ref={mesh}
        name=''
        geometry={nodes.Plane072.geometry}
        material={nodes.Plane072.material}
        position={[7.83, 0, 0]}
        scale={[1, 1.48, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
          color = {isHovered? '#fff' : '#399E5A'}
        />
      </mesh> */}
      {/* //---------TN---------//
      <mesh
        ref={mesh}
        name='TN'
        geometry={nodes.Plane071.geometry}
        material={nodes.Plane071.material}
        position={[4.49, 0, 0.16]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
          color = {isHovered? '#fff' : '#399E5A'}
          />
      </mesh> */}
      {/* //---------ME---------//
      <mesh
        ref={mesh}
        name='ME'
        geometry={nodes.Plane068.geometry}
        material={nodes.Plane068.material}
        position={[10.67, 0, -7.25]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
          color = {isHovered? '#fff' : '#399E5A'}
          />
      </mesh> */}
      {/* //--------- AL ---------//
      <mesh
        ref={mesh}
        name='AL'
        geometry={nodes.Plane067.geometry}
        material={nodes.Plane067.material}
        position={[3.62, 0, 3.05]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
        >
        <meshStandardMaterial
          color = {isHovered? '#fff' : '#399E5A'}
          />
      </mesh> */}
      {/* //---------MS---------//
      <mesh
        ref={mesh}
        name='MS'
        geometry={nodes.Plane066.geometry}
        material={nodes.Plane066.material}
        position={[2.28, 0, 2.83]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
        >
        <meshStandardMaterial
          color = {isHovered? '#fff' : '#399E5A'}
          />
      </mesh> */}
      {/* //---------LA---------//
      <mesh
        ref={mesh}
        name='LA'
        geometry={nodes.Plane065.geometry}
        material={nodes.Plane065.material}
        position={[1.65, 0, 3.89]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
          color = {isHovered? '#fff' : '#399E5A'}
          />
      </mesh> */}
      {/* //---------AR---------//
      <mesh
        ref={mesh}
        name='AR'
        geometry={nodes.Plane064.geometry}
        material={nodes.Plane064.material}
        position={[1.23, 0, 1.13]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
        >
        <meshStandardMaterial
          color = {isHovered? '#fff' : '#399E5A'}
          />
      </mesh> */}
      {/* //---------MO---------//
      <mesh
        ref={mesh}
        name='MO'
        geometry={nodes.Plane063.geometry}
        material={nodes.Plane063.material}
        position={[1.35, 0, -0.98]}
        scale={[1, 1.37, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
          color = {isHovered? '#fff' : '#399E5A'}
          />
      </mesh> */}
      {/* //---------IL---------//
      <mesh
        ref={mesh}
        name='IL'
        geometry={nodes.Plane062.geometry}
        material={nodes.Plane062.material}
        position={[2.07, 0, -1.96]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
          color = {isHovered? '#fff' : '#399E5A'}
          />
      </mesh> */}
      {/* //---------WI---------//
      <mesh
        ref={mesh}
        name='WI'
        geometry={nodes.Plane061.geometry}
        material={nodes.Plane061.material}
        position={[1.56, 0, -5.33]}
        scale={[1, 1.41, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
          color = {isHovered? '#fff' : '#399E5A'}
          />
      </mesh> */}
      {/* //---------MN---------//
      <mesh
        ref={mesh}
        name='MN'
        geometry={nodes.Plane060.geometry}
        material={nodes.Plane060.material}
        position={[0.1, 0, -6.33]}
        scale={[1, 1.51, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
          color = {isHovered? '#fff' : '#399E5A'}
        />
      </mesh> */}
      {/* //---------IA---------//
      <mesh
        ref={mesh}
        name='IA'
        geometry={nodes.Plane059.geometry}
        material={nodes.Plane059.material}
        position={[0.76, 0, -3.35]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
          color = {isHovered? '#fff' : '#399E5A'}
          />
      </mesh> */}
      {/* //---------TX---------//
      <mesh
        ref={mesh}
        name='TX'
        geometry={nodes.Plane058.geometry}
        material={nodes.Plane058.material}
        position={[-2.23, 0, 3.73]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
        >
        <meshStandardMaterial
          color = {isHovered? '#fff' : '#399E5A'}
          />
      </mesh> */}
      {/* //---------OK---------//
      <mesh
        ref={mesh}
        name='OK'
        geometry={nodes.Plane057.geometry}
        material={nodes.Plane057.material}
        position={[-1.95, 0, 1.19]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
            color = {isHovered? '#fff' : '#399E5A'}
        />
      </mesh> */}
      {/* //---------KS----------//
      <mesh
        ref={mesh}
        name='KS'
        geometry={nodes.Plane056.geometry}
        material={nodes.Plane056.material}
        position={[-1.4, 0, -1.4]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
            color = {isHovered? '#fff' : '#399E5A'}
        />
      </mesh> */}
      {/* //---------NE---------//
      <mesh
        ref={mesh}
        name='NE'
        geometry={nodes.Plane055.geometry}
        material={nodes.Plane055.material}
        position={[-2.2, 0, -3.1]}
        scale={[1, 1.52, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
            color = {isHovered? '#fff' : '#399E5A'}
        />
      </mesh> */}
      {/* //---------SD---------//
      <mesh
        ref={mesh}
        name='SD'
        geometry={nodes.Plane054.geometry}
        material={nodes.Plane054.material}
        position={[-2.13, 0, -4.71]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
            color = {isHovered? '#fff' : '#399E5A'}
        />
      </mesh> */}
      {/* //---------ND---------//
      <mesh
        ref={mesh}
        name='ND'
        geometry={nodes.Plane053.geometry}
        material={nodes.Plane053.material}
        position={[-1.91, 0, -6.44]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
        >
          <meshStandardMaterial
            color = {isHovered? '#fff' : '#399E5A'}
        />
      </mesh> */}
      //---------CO---------//
      <mesh
        ref={mesh}
        name='CO'
        geometry={nodes.Plane052.geometry}
        material={nodes.Plane052.material}
        position={[-5.48, 0, -1.66]}
        scale={[1, 1.67, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
        >
          <meshStandardMaterial
            color = {isHovered? '#fff' : '#399E5A'}
        />
      </mesh>
      //--------- NM ---------//
      <mesh
        ref={mesh}
        name='NM'
        geometry={nodes.Plane051.geometry}
        material={nodes.Plane051.material}
        position={[-6.56, 0, 2.09]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
        >
          <meshStandardMaterial
            color = {isHovered? '#fff' : 'blue'}
        />
      </mesh>
      //--------- WY ---------//
      <mesh
        ref={mesh}
        name='WY'
        geometry={nodes.Plane050.geometry}
        material={nodes.Plane050.material}
        position={[-6.13, 0, -4.25]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
        >
          <meshStandardMaterial
            color = {isHovered? '#fff' : 'limegreen'}
        />
      </mesh>
      //--------- UT ---------//
      <mesh 
        ref={mesh}
        name='UT'
        geometry={nodes.Plane031.geometry}
        material={nodes.Plane031.material}
        position={[-8.15, 0, -2.59]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
          <meshStandardMaterial
            color = {isHovered? '#fff' : 'purple'}
        />
      </mesh>
      //--------- AZ ---------//
      <mesh
        ref={mesh}
        name='AZ'
        geometry={nodes.Plane030.geometry}
        material={nodes.Plane030.material}
        position={[-9.84, 0, 0.66]}
        scale={[1, 1.44, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
            color = {isHovered? '#fff' : 'orange'}
        />
      </mesh>
      //--------- MT ---------//
      <mesh
        ref={mesh}
        name='MT'
        geometry={nodes.Plane029.geometry}
        material={nodes.Plane029.material}
        position={[-7.87, 0, -6.75]}
        scale={[1, 1.44, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
            color = {isHovered? '#fff' : 'hotpink'}
        />
      </mesh>
      //---------ID---------//
      <mesh
        ref={mesh}
        name='ID'
        geometry={nodes.Plane028.geometry}
        material={nodes.Plane028.material}
        position={[-9.33, 0, -6.29]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
            color = {isHovered? '#fff' : 'yellow'}
        />
      </mesh>
      //---------NV---------//
      <mesh
        ref={mesh}
        name='NV'
        geometry={nodes.Plane027.geometry}
        material={nodes.Plane027.material}
        position={[-10.32, 0, -1.51]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
            color = {isHovered? '#fff' : 'slategray'}
        />
      </mesh>
      //---------CA---------//
      <mesh
        ref={mesh}
        name='CA'
        geometry={nodes.Plane026.geometry}
        material={nodes.Plane026.material}
        position={[-12.84, 0, -1.7]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
            color = {isHovered? '#fff' : 'steelblue'}
        />
      </mesh>
      //---------OR---------//
      <mesh
        ref={mesh}
        name='OR'
        geometry={nodes.Plane025.geometry}
        material={nodes.Plane025.material}
        position={[-11.41, 0, -6.17]}
        scale={[1, 1.94, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
            color = {isHovered? '#fff' : 'black'}
        />
      </mesh>
      //---------WA---------//
      <mesh 
        ref={mesh}
        name='WA'
        geometry={nodes.Plane024.geometry}
        material={nodes.Plane024.material}
        position={[-11.89, 0, -7.98]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
            color = {isHovered? '#fff' : 'red'}
        />
      </mesh>
      //--------- AK ---------//
      <mesh
        ref={mesh}
        name='AK'
        geometry={nodes.Plane023.geometry}
        material={nodes.Plane023.material}
        position={[-9.38, 0, 6.93]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
            color = {isHovered? '#fff' : '#399E5A'}
        />
      </mesh>
      //--------- HI ---------//
      <mesh
        ref={mesh}
        name='HI'
        geometry={nodes.Plane005.geometry}
        material={nodes.Plane005.material}
        position={[-12.91, 0, 4.66]}
        scale={[1, 1.29, 1]}
        onPointerOver={e => onHover(e, true)}
        onPointerOut={e => onHover(e, false)}
        onClick={() => handleClick()}
      >
        <meshStandardMaterial
            // color = {isHovered? '#fff' : '#399E5A'}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/states/usa.glb')

