/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function NC({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/NorthCarolina.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh 
        geometry={nodes.Plane072.geometry} 
        material={materials['Material.001']} 
        position={[7.83, 0, 0]} 
      >
      <meshStandardMaterial
            color = {isHovered? '#fff' : '#399E5A'}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/NorthCarolina.glb')
